const fs = require('fs');
const path = 'integrations/google-apps-script/psc_wdb_web_app.gs';
const text = fs.readFileSync(path, 'utf8');
if (!text.includes('scheduleRow: null') || !text.includes('intakeRow: [')) throw new Error('intake patch markers missing');
if (!text.includes('opts.intakeRow')) throw new Error('intake writer missing');
const row = ['', '', '2026-09-18', 'เฮียหนิง', '', 'กะหล่ำปลี', '', '', '', 7425, '', '', '', '', '', 74.93, 'สภาพโดยรวมสวย; สุ่มปอก 100 กก.; ปอกได้ 74.93 กก.', 'รับเข้าเรียบร้อย', ''];
if (row.length !== 19) throw new Error(`expected 19 columns, got ${row.length}`);
console.log('intake patch markers OK; sample row columns:', row.length);
console.log('source bytes:', text.length);
นัก = undefined;
fs.writeFileSync('/tmp/pscdb_validation_marker.txt', 'validated\n');
console.log('validated');
ต = undefined;
console.log('done');
