//+------------------------------------------------------------------+
//|                                         MT5_CMD_Dashboard_EA.mq5 |
//|                                      Generated by AGY / Antigravity |
//+------------------------------------------------------------------+
#property copyright "AGY"
#property link      ""
#property version   "2.00"

input int RefreshRateMs = 1000; // Refresh rate in milliseconds

int OnInit()
{
   EventSetMillisecondTimer(RefreshRateMs);
   Print("MT5 Terminal Dashboard EA v2.0 Started. Exporting to Common/Files/mt5_dashboard.json");
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   EventKillTimer();
   Print("MT5 Terminal Dashboard EA Stopped.");
}

void OnTimer()
{
   int total_positions = PositionsTotal();
   double total_profit = 0;
   double total_volume = 0;
   
   string pos_json = "[";
   for(int i=0; i<total_positions; i++)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
      {
         double profit = PositionGetDouble(POSITION_PROFIT);
         double volume = PositionGetDouble(POSITION_VOLUME);
         string symbol = PositionGetString(POSITION_SYMBOL);
         long type = PositionGetInteger(POSITION_TYPE);
         double price_open = PositionGetDouble(POSITION_PRICE_OPEN);
         double price_current = PositionGetDouble(POSITION_PRICE_CURRENT);
         
         total_profit += profit;
         total_volume += volume;
         
         if(i > 0) pos_json += ",";
         pos_json += "{";
         pos_json += "\"ticket\":" + IntegerToString(ticket) + ",";
         pos_json += "\"symbol\":\"" + symbol + "\",";
         pos_json += "\"type\":\"" + (type == POSITION_TYPE_BUY ? "BUY" : "SELL") + "\",";
         pos_json += "\"lots\":" + DoubleToString(volume, 2) + ",";
         pos_json += "\"open\":" + DoubleToString(price_open, 5) + ",";
         pos_json += "\"current\":" + DoubleToString(price_current, 5) + ",";
         pos_json += "\"profit\":" + DoubleToString(profit, 2);
         pos_json += "}";
      }
   }
   pos_json += "]";

   string json = "{";
   json += "\"AccountName\":\"" + AccountInfoString(ACCOUNT_NAME) + "\",";
   json += "\"AccountNumber\":" + IntegerToString(AccountInfoInteger(ACCOUNT_LOGIN)) + ",";
   json += "\"Currency\":\"" + AccountInfoString(ACCOUNT_CURRENCY) + "\",";
   json += "\"Server\":\"" + AccountInfoString(ACCOUNT_SERVER) + "\",";
   json += "\"Leverage\":\"1:" + IntegerToString(AccountInfoInteger(ACCOUNT_LEVERAGE)) + "\",";
   json += "\"Balance\":" + DoubleToString(AccountInfoDouble(ACCOUNT_BALANCE), 2) + ",";
   json += "\"Equity\":" + DoubleToString(AccountInfoDouble(ACCOUNT_EQUITY), 2) + ",";
   json += "\"Margin\":" + DoubleToString(AccountInfoDouble(ACCOUNT_MARGIN), 2) + ",";
   json += "\"MarginFree\":" + DoubleToString(AccountInfoDouble(ACCOUNT_MARGIN_FREE), 2) + ",";
   json += "\"MarginLevel\":" + DoubleToString(AccountInfoDouble(ACCOUNT_MARGIN_LEVEL), 2) + ",";
   json += "\"OpenPositions\":" + IntegerToString(total_positions) + ",";
   json += "\"TotalVolume\":" + DoubleToString(total_volume, 2) + ",";
   json += "\"FloatingProfit\":" + DoubleToString(total_profit, 2) + ",";
   json += "\"Positions\":" + pos_json;
   json += "}";

   int file_handle = FileOpen("mt5_dashboard.json", FILE_WRITE|FILE_TXT|FILE_COMMON);
   if(file_handle != INVALID_HANDLE)
   {
      FileWriteString(file_handle, json);
      FileClose(file_handle);
   }
}
